# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'study29_firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for study29_firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
end
